version: '3.5'

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: $PHP_CONTAINER_NAME
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true