version: '3.5'

services:
  app:
    build: ./docker/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge